### ISSUE TITLE
import only specific lodash functions

### ISSUE THREAD

**Issue by nathanloisel** [maimArt/typescript-immutable-helper#4]
Hi,

The project is cool and i'm interessed by using it. I see that some small improvment can be done.
You can remove the lodash npm dependency and replace it by lodash.get, lodash.set, lodash.clonedeep, it's lighter.
Nice work :D

**Comment by maimArt** [comment]
Hi,

thank you for your feedback. Implemented and released it with 0.6.3.

Greets
